"""
Django settings for ENPYBase project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': 'unix:/tmp/memcached.sock',
#     },
#     'cache-for-ratelimiting': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': 'unix:/tmp/memcached.sock',
#     },
# }


# RATELIMIT_USE_CACHE = 'cache-for-ratelimiting'



ALLOWED_HOSTS = [os.environ.get("ALLOWED_HOST_ONE"), os.environ.get("ALLOWED_HOST_TWO"),
                 os.environ.get("ALLOWED_HOST_THREE")]

# RATELIMIT_KEY = 'user' # or any other key that you want to use
# RATELIMIT_FAIL_OPEN=True
RATELIMIT_VIEW = 'enpyapp.views.ratelimited_error'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djongo',
    'enpyapp',
    'ratelimit',
    # 'django-ratelimit'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'ratelimit.middleware.RatelimitMiddleware'
]

ROOT_URLCONF = 'ENPYBase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ENPYBase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

USER = os.environ.get("MONGO_USER")
PASS = os.environ.get("MONGO_PASS")
MONGO_URI = os.environ.get("MONGO_URI")

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.dummy',
    # },
    'default': {
        'ENGINE': 'djongo',
        'CLIENT': {
            'name': 'ENPY',
            'host': f'mongodb+srv://{USER}:{PASS}@enpy.{MONGO_URI}.mongodb.net/?retryWrites=true&w=majority',
            'username': USER,
            'password': PASS,
            'authSource': 'admin',
            'authMechanism': 'SCRAM-SHA-1',
            'retryWrites': True,
            'w': 'majority'
        },
    },
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
